server.port=7035
app.frontend-url=https://localhost:3000
app.on-production=false

stripe.dev.public-key=xxx
stripe.dev.private-key=xxx
stripe.dev.lookup-key=xxx
stripe.prod.public-key=pk_live_51QQsbkG3TGHQ3eAXYejRlflVpUtOe6pXXw0MMWMl79r8Fkn5KPz205z5LZpWav34vWbBAQgtdeXSTXIbs7PbEF0f00EzPez44K
stripe.prod.private-key=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
stripe.prod.lookup-key=unlimited_ip_api